DBI.Safety/DBI.Safety/Controllers/SOCController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using DBI.Safety.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Dapper;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using DBI.Safety.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;

namespace DBI.Safety.Controllers
{
    [Authorize]
    public class SOCController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly IHostingEnvironment environment;
        private string defaultConnectionString { get; set; }
        private string appSafetyDb { get; set; }
        public SOCController(IConfiguration config, IHostingEnvironment env)
        {
            this.configuration = config;
            this.environment = env;

            if (environment.EnvironmentName == "Development" || environment.EnvironmentName == "Staging")
            {
                this.defaultConnectionString = "DefaultStagingConnection";
                this.appSafetyDb = "AppSafetyTestDb";
            }
            else
            {
                this.defaultConnectionString = "DefaultConnection";
                this.appSafetyDb = "AppSafetyDb";
            }
        }        

        public JsonResult GetTaskList(string locationId)
        {
            SqlConnection unifiedConn = new SqlConnection();
            unifiedConn.ConnectionString = configuration.GetConnectionString("UnifiedCatalogConnection");
            using (IDbConnection dbConnection = unifiedConn)
            {
                dbConnection.Open();

                var userInfo = dbConnection.Query<dynamic>
                    ("App_sel_UserAccounts2", new
                    {
                        WindowsAccount = this.User.Identity.Name
                    },
                    commandType: CommandType.StoredProcedure).FirstOrDefault();

                List<SelectListItemV2> taskList = new List<SelectListItemV2>();

                if (userInfo != null)
                {
                    if (userInfo.BusinessUnit == "11 - DBI")
                    {
                        var locationName = dbConnection.Query<string>(@"SELECT location
                                  FROM [AppUnifiedCatalogDb].[dbo].[DARProjects]
                                  WHERE segment1 = @LocationId", new { @LocationId = locationId }).FirstOrDefault();

                        taskList = dbConnection.Query<SelectListItemV2>
                        ("App_Sel_ValueNamePair", new
                        {
                            pairName = "DARTask_ByLocation",
                            IntVar1 = 0,
                            IntVar2 = 0,
                            StrVar1 = locationName,
                            StrVar2 = ""
                        },
                        commandType: CommandType.StoredProcedure).ToList();
                    }
                    else if (userInfo.BusinessUnit == "41 - DBIS")
                    {
                        taskList = dbConnection.Query<SelectListItemV2>
                        ("App_Sel_ValueNamePair", new
                        {
                            pairName = "DARTask_BySegment1",
                            IntVar1 = 0,
                            IntVar2 = 0,
                            StrVar1 = locationId,
                            StrVar2 = ""
                        },
                        commandType: CommandType.StoredProcedure).ToList();
                    }

                    taskList.Insert(0, new SelectListItemV2 { ValueMember = "0", DisplayMember = "Select" });
                    taskList.Insert(1, new SelectListItemV2 { ValueMember = "34", DisplayMember = "Office Work" });
                    taskList.Insert(2, new SelectListItemV2 { ValueMember = "35", DisplayMember = "Shop Work" });
                }

                dbConnection.Close();
                
                return Json(new SelectList(taskList, "ValueMember", "DisplayMember"));
            }            
        }

        public JsonResult GetTaskFilterList(int locationId)
        {
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = configuration.GetConnectionString(defaultConnectionString);
            using (IDbConnection dbConnection = conn)
            {
                dbConnection.Open();
                List<SelectListItemV2> taskList = dbConnection.Query<SelectListItemV2>(@"SELECT DISTINCT s.Task AS ValueMember, '(' + t.task_number + ')' +
                    CASE WHEN LEN(t.task_description) > 0 THEN ' - ' +  t.task_description ELSE '' END AS DisplayMember                    
                    FROM " + appSafetyDb + @".dbo.SOCDataV2 s
                    INNER JOIN AppUnifiedCatalogDb.dbo.DARTask t ON s.Task = t.task_id WHERE s.Location = @location", new { @Location = locationId }).ToList();                
                dbConnection.Close();

                taskList.Insert(0, new SelectListItemV2 { ValueMember = "0", DisplayMember = "All" });
                taskList.Insert(1, new SelectListItemV2 { ValueMember = "34", DisplayMember = "Office Work" });
                taskList.Insert(2, new SelectListItemV2 { ValueMember = "35", DisplayMember = "Shop Work" });
                return Json(new SelectList(taskList, "ValueMember", "DisplayMember"));
            }
        }

        public SOCForm GetSOCForm(SOCForm activeForm = null)
        {
            SOCForm form = new SOCForm();

            SqlConnection unifiedConn = new SqlConnection();
            unifiedConn.ConnectionString = configuration.GetConnectionString("UnifiedCatalogConnection");
            using (IDbConnection dbConnection = unifiedConn)
            {
                dbConnection.Open();

                var userInfo = dbConnection.Query<dynamic>
                    ("App_sel_UserAccounts2", new
                    {
                        WindowsAccount = this.User.Identity.Name
                    },
                    commandType: CommandType.StoredProcedure).FirstOrDefault();

                List<SelectListItemV2> locationList = new List<SelectListItemV2>();
                string locationProcName = string.Empty;

                if (userInfo != null)
                {                    
                    if (userInfo.BusinessUnit == "11 - DBI")
                    {
                        locationProcName = "DARProjects_ByEmployee2";                                      
                    } 
                    else if(userInfo.BusinessUnit == "41 - DBIS")
                    {
                        locationProcName = "DARProjects_ByEmployee3b"; 
                    }
                }

                locationList = dbConnection.Query<SelectListItemV2>
                    ("App_Sel_ValueNamePair", new
                    {
                        pairName = locationProcName,
                        IntVar1 = 0,
                        IntVar2 = 0,
                        StrVar1 = this.User.Identity.Name,
                        StrVar2 = "SafetyApp"
                    },
                    commandType: CommandType.StoredProcedure).ToList();

                locationList.Insert(0, new SelectListItemV2()
                {
                    ValueMember = "0",
                    DisplayMember = "Please select location"
                });

                form.LocationList = locationList;

                if (activeForm != null)
                {
                    if (!string.IsNullOrEmpty(activeForm.SelectedLocationId))
                    {
                        List<SelectListItemV2> taskList = new List<SelectListItemV2>();

                        if (userInfo != null)
                        {
                            if (userInfo.BusinessUnit == "11 - DBI")
                            {
                                var locationName = dbConnection.Query<string>(@"SELECT location
                                  FROM [AppUnifiedCatalogDb].[dbo].[DARProjects]
                                  WHERE segment1 = @LocationId", new { @LocationId = activeForm.SelectedLocationId }).FirstOrDefault();

                                taskList = dbConnection.Query<SelectListItemV2>
                                ("App_Sel_ValueNamePair", new
                                {
                                    pairName = "DARTask_ByLocation",
                                    IntVar1 = 0,
                                    IntVar2 = 0,
                                    StrVar1 = locationName,
                                    StrVar2 = ""
                                },
                                commandType: CommandType.StoredProcedure).ToList();
                            }
                            else if (userInfo.BusinessUnit == "41 - DBIS")
                            {
                                taskList = dbConnection.Query<SelectListItemV2>
                                ("App_Sel_ValueNamePair", new
                                {
                                    pairName = "DARTask_BySegment1",
                                    IntVar1 = 0,
                                    IntVar2 = 0,
                                    StrVar1 = activeForm.SelectedLocationId,
                                    StrVar2 = ""
                                },
                                commandType: CommandType.StoredProcedure).ToList();
                            }

                            taskList.Insert(0, new SelectListItemV2() { ValueMember = "0", DisplayMember = "Please select task" });
                            taskList.Insert(1, new SelectListItemV2 { ValueMember = "34", DisplayMember = "Office Work" });
                            taskList.Insert(2, new SelectListItemV2 { ValueMember = "35", DisplayMember = "Shop Work" });

DBI.Safety/DBI.Safety/Views/Shared/_DevExtremeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DBI_Safety</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <script src="~/js/devextreme/cldr.js"></script>
    <script src="~/js/devextreme/cldr/event.js"></script>
    <script src="~/js/devextreme/cldr/supplemental.js"></script>
    <script src="~/js/devextreme/cldr/unresolved.js"></script>

    <script src="~/js/devextreme/globalize.js"></script>
    <script src="~/js/devextreme/globalize/message.js"></script>
    <script src="~/js/devextreme/globalize/number.js"></script>
    <script src="~/js/devextreme/globalize/currency.js"></script>
    <script src="~/js/devextreme/globalize/date.js"></script>

    @* JSZip for client side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@
    
    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/vectormap-data/world.js"></script>
    <script src="~/lib/devextreme-aspnet-data/js/dx.aspnet.data.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>

</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">DBI_Safety</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>
</body>

</html>

DBI.Safety/DBI.Safety/Views/Shared/_Layout.cshtml
@using System.IO;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DBI.Safety</title>

    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:100' rel='stylesheet' type='text/css'>
    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.js"></script>    
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>*@

    <script src="~/js/devextreme/cldr.js"></script>
    <script src="~/js/devextreme/cldr/event.js"></script>
    <script src="~/js/devextreme/cldr/supplemental.js"></script>
    <script src="~/js/devextreme/cldr/unresolved.js"></script>

    <script src="~/js/devextreme/globalize.js"></script>
    <script src="~/js/devextreme/globalize/message.js"></script>
    <script src="~/js/devextreme/globalize/number.js"></script>
    <script src="~/js/devextreme/globalize/currency.js"></script>
    <script src="~/js/devextreme/globalize/date.js"></script>

    @* JSZip for client side export *@
    <script src="~/js/devextreme/jszip.js"></script>

    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/vectormap-data/world.js"></script>
    <script src="~/lib/devextreme-aspnet-data/js/dx.aspnet.data.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <script>
        //// detect IE11
        //if (!!window.MSInputMethodContext && !!document.documentMode) {

        //    var locationOptions = {};
        //    locationOptions = {
        //        enableHighAccuracy: false,
        //        maximumAge: 50000
        //    }

        //    function setCurrentPos(event, firstLoad) {
        //        navigator.geolocation.getCurrentPosition(function (position) {
        //            positionSuccess
        //        }, function (error) {
        //            positionError
        //        }, locationOptions);
        //    }
        //} else {}

        var options = {
            enableHighAccuracy: true,
            timeout: 5000,
            maximumAge: 0
        };

        navigator.geolocation.getCurrentPosition(positionSuccess, positionError, options);                    

        function positionSuccess(geo) {
            document.cookie = 'latitude=' + String(geo.coords.latitude);
            document.cookie = 'longitude=' + String(geo.coords.longitude);
            document.cookie = 'accuracy=' + String(geo.coords.accuracy);
        }

        function positionError(geo) {
            document.cookie = 'latitude=; expires=Thu, 01 Jan 1970 00:00:00 UTC;';
            document.cookie = 'longitude=; expires=Thu, 01 Jan 1970 00:00:00 UTC;';
            document.cookie = 'accuracy=; expires=Thu, 01 Jan 1970 00:00:00 UTC;';
        }
        
    </script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="border-bottom: 5px solid #ae8310;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <span>@Html.Raw(File.ReadAllText("wwwroot/images/Logo_pub.svg"))</span>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            SOC
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="SOC" asp-action="Create">Create New SOC</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="SOC" asp-action="History">SOC History</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            FLHA
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="FLHA" asp-action="Create">Create New FLHA</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="FLHA" asp-action="History">FLHA History</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AddForm">Add Form</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AddCategory">Add Category</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AddDictionary">Add Dictionary</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AddRegionalManager">Add Regional Manager</a></li>                            
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Reports
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Reports" asp-action="SocTotalNumber">SOC Reports</a></li>
                            @*<li><a class="dropdown-item" target="_blank" href="http://s0077.dbiservices.com/ReportS/report/SafetyApp/CountsForSoc">SOC Details</a></li>*@
                        </ul>
                    </li>
                </ul>
                <form asp-action="Logout">
                    <p class="nav navbar-text navbar-right">
                        Hello, @User.Identity.Name |
                        <input class="btn-link" type="submit" value="Logout" asp-controller="Account" asp-action="Logout" />
                    </p>
                </form>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    <div class="footer navbar-fixed-bottom hidden-print">
        <p>&copy; 2018 - DBi Services: Safety</p>
    </div>
    <div class="footer-printer navbar-fixed-bottom visible-print-block">
        <p>&copy; 2018 - DBi Services: Safety</p>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

DBI.Safety/DBI.Safety/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DBI.Safety</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/login.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/login.min.css" asp-append-version="true" />
    </environment>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:100' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class="limiter">
        <div class="container-login100">
            @RenderBody()
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>